import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./redux/redux/provider";
import { store } from "./redux/redux/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const  partnerName= store.getState().partner.partnerName;
  console.log(partnerName);
  return (
    <html lang="en">
      <body className={inter.className}>
        {partnerName?partnerName:'No set partner'}
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
